#!/bin/sh

# Variables
BRIDGE=brWan
SCRIPT=`basename "$0"`

# Make sure the script is indeed invoked
touch /tmp/000-$SCRIPT

logger -t $SCRIPT "firewall-start: applying INPUT rules for brWan"

# Allow new incoming connections from brWan
iptables -I INPUT -i $BRIDGE -m state --state NEW -j ACCEPT

# Only forbid brWan access the web UI and SSH of the main router
#iptables -I INPUT -i $BRIDGE -p tcp --dport 80 -j DROP
#iptables -I INPUT -i $BRIDGE -p tcp --dport 22 -j DROP

logger -t $SCRIPT "firewall-start: applying FORWARD rules for brWan"

# Forbid packets from brWan to be forwarded to other interfaces
iptables -I FORWARD -i $BRIDGE -j DROP

# But allow packet forwarding inside brWan
iptables -I FORWARD -i $BRIDGE -o $BRIDGE -j ACCEPT

# Allow packet forwarding between brWan and eth4 (WAN)
iptables -I FORWARD -i $BRIDGE -o eth4 -j ACCEPT

# Allow packet forwarding between brWan and tun12 (VPN)
iptables -I FORWARD -i $BRIDGE -o tun12 -j ACCEPT

logger -t $SCRIPT "firewall-start: all done"
