#!/bin/sh

# Make sure the script is indeed invoked
touch /tmp/000-services-start

# Physical port to interface map:
# eth0   LAN 4
# eth1   LAN 3
# eth2   LAN 2
# eth3   LAN 1
# eth4   WAN 
# eth5   2.4 GHz Radio
# eth6   5 GHz Radio
# wl0.3  2.4 GHz Radio Guest Network 3
# wl1.3  5 GHz Radio Guest Network 3

ethswctl -c hw-switching -o disable

logger -t "Running Script" "/jffs/scripts/gurulandia/services/vlan-2000-service"
/jffs/scripts/gurulandia/services/vlan-2000-service

logger -t "Running Script" "/jffs/scripts/gurulandia/services/vlan-44-service"
/jffs/scripts/gurulandia/services/vlan-44-service

logger -t "Running Script" "/jffs/scripts/gurulandia/services/vlan-0-service"
/jffs/scripts/gurulandia/services/vlan-0-service



