#!/bin/sh

# Variables
BASEPORT=eth0
VLANID=0
BRIDGE=br0
SCRIPT=`basename "$0"`

# Make sure the script is indeed invoked
touch /tmp/000-$SCRIPT

# Create the new subinterface for eth0 to be the Native VLAN (Untagged)
logger -t $SCRIPT "services-start: Create VLAN 0 to LAN 4 (eth0.v0)"
vlanctl --if-create $BASEPORT $VLANID
vlanctl --if $BASEPORT --rx --tags 0 --set-rxif $BASEPORT.v$VLANID --rule-append
vlanctl --if $BASEPORT --tx --tags 0 --filter-txif $BASEPORT.v$VLANID --rule-append
ifconfig $BASEPORT.v$VLANID up
brctl addif $BRIDGE $BASEPORT.v$VLANID

logger -t $SCRIPT "services-start: all done"
